### ISSUE TITLE
Pod doesn't exist

### ISSUE THREAD

**Issue by henryhardy** [kwallet/planet#3]
Hiya.

You currently can't import this as a pod as it doesn't exist in the pods repo at the moment.

Just letting you know.

**Comment by kmikael** [comment]
What do you mean? It's right here for me? https://github.com/CocoaPods/Specs/blob/fea11f7ac0333be3b6c87da49993dbf234c89429/Specs/Planet/0.1.0/Planet.podspec.json

I was also able to import it. Did you try updating your local specs with `pod repo update`?

**Comment by henryhardy** [comment]
Yeah.. i found if i put it straight into my pod file as just pod 'Planet' it would throw an error, but if i pointed it to the this repo directly it worked ok. Great/Epic pod though =]

ie pod 'Planet' throws the error
Analyzing dependencies
[!] Unable to find a specification for `Planet`

where as if i go   pod 'Planet', :git => 'https://github.com/digitalassetgroup/planet.git' (i forked it)
it works fine.

**Comment by kmikael** [comment]
Good to hear you solved the problem.

I should work with just `pod 'Planet'` after you do `pod repo update`. Since CocoaPods 1.0 this doesn't happen automatically when you do `pod install`.
